### ISSUE TITLE
PHASE 02 - ITEARATION 25 MARCH SUBMISSION DELIVERABLES

### ISSUE THREAD

**Issue by aysegulaksu** [582-41W-VA/web-project-2-team-bookreview#12]
- Visual language guidelines: Typography, colors, and grid system will be carefully chosen to reflect the preferences of the organization and project identity. It will enhance accessibility for the diverse user segments identified. Design decisions will be justified based on their ability to create consistency, structure, and visual appeal across the website.
- Wireframes: One for each page, accompanied by a rationale outlining how the layout and design decisions align with the preferences and expectations of the identified user segments, and the identity of the company and the project.
-   Semantic Data Model (Entity-Relationship Diagram):An ER diagram illustrating the relationships between entities in the data model, with a rationale outlining how the data structure supports the functionality and user interactions required for each user segment.
- Completing technical set up: Completing setup for all tools and technologies such as Django framework, integration of necessary frontend and backend technologies, etc.
- README File: A comprehensive document detailing the project's architecture, installation instructions, and how to run it locally.
-   Admin Login Functionality: Functioning admin login page with authentication and authorization mechanisms in place.
- Source Code: Sharing source code for the completed sections, including docstrings and testing.

**Comment by aysegulaksu** [comment]
Visual language guidelines ( ✔)
Wireframes: ( ✔)
Semantic Data Model (Entity-Relationship Diagram):( ✔)
Completing technical set up: ( ✔)
README File: A comprehensive document detailing the project's architecture, installation instructions, and how to run it locally.
Admin Login Functionality ( ✔)
Sharing source code for the completed sections ( ✔)

**Comment by aysegulaksu** [comment]
All submissions that include coding are located on the GitHub main branch.
Submissions containing text documents, reports, and visual content such as images and graphics can be accessed on the team website: [Team Website Link](https://aysegul90.web582.com/webproject/index.html).
Visual language guidelines ( ✔) can be found on the team website as well, with the link provided: [Visual Guideline Link](https://aysegul90.web582.com/webproject/phase2design.html).
Wireframes ( ✔) are also available on the team website via the following link: [Wireframes Link](https://aysegul90.web582.com/webproject/wireframes.html).
The Semantic Data Model (Entity-Relationship Diagram) ( ✔) is accessible through the provided link: [Model Link](https://aysegul90.web582.com/webproject/database.html).
Technical setup completion ( ✔) has been confirmed. Additionally, a comprehensive README file has been provided, detailing the project's architecture, installation instructions, and how to run it locally.
Admin Login Functionality ( ✔) can be found on the GitHub main branch.
Source code for the completed sections ( ✔) is available on the GitHub main branch as well.

**Comment by HHHuser1** [comment]
README for installing project and DOCSTRINGS will be completed towards the end of phase 2.
